local Music = require("scripts.musicapi.enums")

--[[
Music triggers will replace (or supplement) normal music callbacks.

With the current API, you can only check for a music track and replace it without any context.
This should rectify that, making music replacements for specific scenarios easier, (Eg. Mega
Satan, Hush stage 1) especially where music is reused. This also allows mods to simply disable
trigger tags, for example JINGLE_BOSS, so that no boss jingles ever play, jumping straight into
the boss theme.

This mostly affects Soundtrack Menu. As of right now, it has a special case for Mega Satan, but
this update should make it so that no special cases are needed at all.

If you have a surplus of music from another source to put into Isaac, you can use this trigger
system to add separate tracks to Basement I and Basement II for example rather than add it to
the entire Basement, if you want.
Conversely, if you do not have enough music, you can make tracks simply not play or redirect to
other tracks. For example: Have one track cover all boss music by looking for the "BOSS" tag.

The "REPENTANCE" tag is added to all repentance triggers. If there was a music mod from Afterbirth+
that you would like to convert into a repentance soundtrack, you can use this tag to determine
if the music will be replaced successfully or not, and it can be redirected.
]]

MusicAPI.AddTrigger("STAGE_BASEMENT", Music.MUSIC_BASEMENT, {"STAGE", "STAGETYPE_ORIGINAL", "STAGE1_1", "STAGE1_2", "STAGE1", "STAGE1_GREED"})
MusicAPI.AddTrigger("STAGE_CELLAR", Music.MUSIC_CAVES, {"STAGE", "STAGETYPE_WOTL", "STAGE1_1", "STAGE1_2", "STAGE1", "STAGE1_GREED"})
MusicAPI.AddTrigger("STAGE_BURNING_BASEMENT", Music.MUSIC_BURNING_BASEMENT, {"STAGE", "STAGETYPE_AFTERBIRTH", "STAGE1_1", "STAGE1_2", "STAGE1", "STAGE1_GREED"})
MusicAPI.AddTrigger("STAGE_DOWNPOUR", Music.MUSIC_DOWNPOUR, {"STAGE", "REPENTANCE", "DIMENSION_0", "STAGETYPE_REPENTANCE", "STAGE1_1", "STAGE1_2", "STAGE1", "STAGE1_GREED"})
MusicAPI.AddTrigger("STAGE_DROSS", Music.MUSIC_DROSS, {"STAGE", "REPENTANCE", "DIMENSION_0", "STAGETYPE_REPENTANCE_B", "STAGE1_1", "STAGE1_2", "STAGE1", "STAGE1_GREED"})
MusicAPI.AddTrigger("STAGE_MIRROR_DOWNPOUR", Music.MUSIC_DOWNPOUR_REVERSE, {"STAGE", "REPENTANCE", "DIMENSION_1", "STAGETYPE_REPENTANCE", "STAGE1_2", "STAGE1", "STAGE1_GREED",})
MusicAPI.AddTrigger("STAGE_MIRROR_DROSS", Music.MUSIC_DROSS_REVERSE, {"STAGE", "REPENTANCE", "DIMENSION_1", "STAGETYPE_REPENTANCE_B", "STAGE1_2", "STAGE1", "STAGE1_GREED"})

MusicAPI.AddTrigger("STAGE_CAVES", Music.MUSIC_CAVES, {"STAGE", "STAGETYPE_ORIGINAL", "STAGE2_1", "STAGE2_2", "STAGE2", "STAGE2_GREED"})
MusicAPI.AddTrigger("STAGE_CATACOMBS", Music.MUSIC_CATACOMBS, {"STAGE", "STAGETYPE_WOTL", "STAGE2_1", "STAGE2_2", "STAGE2", "STAGE2_GREED"})
MusicAPI.AddTrigger("STAGE_FLOODED_CAVES", Music.MUSIC_FLOODED_CAVES, {"STAGE", "STAGETYPE_AFTERBIRTH", "STAGE2_1", "STAGE2_2", "STAGE2", "STAGE2_GREED"})
MusicAPI.AddTrigger("STAGE_MINES", Music.MUSIC_MINES, {"STAGE", "REPENTANCE", "DIMENSION_0", "STAGETYPE_REPENTANCE", "STAGE2_1", "STAGE2_2", "STAGE2", "STAGE2_GREED"})
MusicAPI.AddTrigger("STAGE_ASHPIT", Music.MUSIC_ASHPIT, {"STAGE", "REPENTANCE", "DIMENSION_0", "STAGETYPE_REPENTANCE_B", "STAGE2_1", "STAGE2_2", "STAGE2", "STAGE2_GREED"})
MusicAPI.AddTrigger("STAGE_MINESHAFT_AMBIENT", Music.MUSIC_MINESHAFT_AMBIENT, {"STAGE", "REPENTANCE", "DIMENSION_1", "STAGETYPE_REPENTANCE", "STAGETYPE_REPENTANCE_B", "STAGE2_2", "STAGE2"})
MusicAPI.AddTrigger("STAGE_MINESHAFT_ESCAPE", Music.MUSIC_MINESHAFT_ESCAPE, {"STAGE", "REPENTANCE", "DIMENSION_1", "STAGETYPE_REPENTANCE", "STAGETYPE_REPENTANCE_B", "STAGE2_2", "STAGE2"})

MusicAPI.AddTrigger("STAGE_DEPTHS", Music.MUSIC_CAVES, {"STAGE", "STAGETYPE_ORIGINAL", "STAGE3_1", "STAGE3_2", "STAGE3", "STAGE3_GREED"})
MusicAPI.AddTrigger("STAGE_NECROPOLIS", Music.MUSIC_NECROPOLIS, {"STAGE", "STAGETYPE_WOTL", "STAGE3_1", "STAGE3_2", "STAGE3", "STAGE3_GREED"})
MusicAPI.AddTrigger("STAGE_DANK_DEPTHS", Music.MUSIC_DANK_DEPTHS, {"STAGE", "STAGETYPE_AFTERBIRTH", "STAGE3_1", "STAGE3_2", "STAGE3", "STAGE3_GREED"})
MusicAPI.AddTrigger("STAGE_MAUSOLEUM", Music.MUSIC_MAUSOLEUM, {"STAGE", "REPENTANCE", "STAGETYPE_REPENTANCE", "STAGE3_1", "STAGE3_2", "STAGE3", "STAGE3_GREED"})
MusicAPI.AddTrigger("STAGE_GEHENNA", Music.MUSIC_GEHENNA, {"STAGE", "REPENTANCE", "STAGETYPE_REPENTANCE_B", "STAGE3_1", "STAGE3_2", "STAGE3", "STAGE3_GREED"})

MusicAPI.AddTrigger("STAGE_WOMB", Music.MUSIC_WOMB_UTERO, {"STAGE", "STAGETYPE_ORIGINAL", "STAGE4_1", "STAGE4_2", "STAGE4", "STAGE4_GREED"})
MusicAPI.AddTrigger("STAGE_UTERO", Music.MUSIC_UTERO, {"STAGE", "STAGETYPE_WOTL", "STAGE4_1", "STAGE4_2", "STAGE4", "STAGE4_GREED"})
MusicAPI.AddTrigger("STAGE_SCARRED_WOMB", Music.MUSIC_SCARRED_WOMB, {"STAGE", "STAGETYPE_AFTERBIRTH", "STAGE4_1", "STAGE4_2", "STAGE4", "STAGE4_GREED"})
MusicAPI.AddTrigger("STAGE_CORPSE", Music.MUSIC_CORPSE, {"STAGE", "REPENTANCE", "STAGETYPE_REPENTANCE", "STAGE4_1", "STAGE4_2", "STAGE4", "STAGE4_GREED"})
MusicAPI.AddTrigger("STAGE_MORTIS", Music.MUSIC_MORTIS, {"STAGE", "REPENTANCE", "STAGETYPE_REPENTANCE_B", "STAGE4_1", "STAGE4_2", "STAGE4", "STAGE4_GREED"})

MusicAPI.AddTrigger("STAGE_BLUE_WOMB", Music.MUSIC_BLUE_WOMB, {"STAGE", "STAGE4_3", "STAGE4"})

MusicAPI.AddTrigger("STAGE_SHEOL", Music.MUSIC_SHEOL, {"STAGE", "STAGETYPE_ORIGINAL", "STAGE5", "STAGE5_GREED"})
MusicAPI.AddTrigger("STAGE_CATHEDRAL", Music.MUSIC_CATHEDRAL, {"STAGE", "STAGETYPE_WOTL", "STAGE5", "STAGE5_GREED"})

MusicAPI.AddTrigger("STAGE_DARK_ROOM", Music.MUSIC_DARK_ROOM, {"STAGE", "STAGETYPE_ORIGINAL", "STAGE6"})
MusicAPI.AddTrigger("STAGE_CHEST", Music.MUSIC_CHEST, {"STAGE", "STAGETYPE_WOTL", "STAGE6"})
MusicAPI.AddTrigger("STAGE_SHOP", Music.MUSIC_SHOP_ROOM, {"STAGE", "STAGE6_GREED"})

MusicAPI.AddTrigger("STAGE_VOID", Music.MUSIC_VOID, {"STAGE", "STAGE7"})
MusicAPI.AddTrigger("STAGE_ULTRA_GREED", Music.MUSIC_SHOP_ROOM, {"STAGE", "STAGE7_GREED"})

MusicAPI.AddTrigger("STAGE_HOME", Music.MUSIC_ISAACS_HOUSE, {"STAGE", "STAGETYPE_ORIGINAL", "STAGE8"})
MusicAPI.AddTrigger("STAGE_DARK_HOME", Music.MUSIC_DARK_CLOSET, {"STAGE", "STAGETYPE_WOTL", "STAGE8"})

MusicAPI.AddTrigger("BOSS_REBIRTH", Music.MUSIC_BOSS, {"BOSS", "BOSS_GENERIC"})
MusicAPI.AddTrigger("BOSS_AFTERBIRTH", Music.MUSIC_BOSS2, {"BOSS", "BOSS_GENERIC"})
MusicAPI.AddTrigger("BOSS_REPENTANCE", Music.MUSIC_BOSS3, {"BOSS", "BOSS_GENERIC", "REPENTANCE"})
MusicAPI.AddTrigger("BOSS_MOM", Music.MUSIC_MOM_BOSS, {"BOSS", "STAGE3_2"})
MusicAPI.AddTrigger("BOSS_MOMS_HEART_WOMB", Music.MUSIC_MOMS_HEART_BOSS, {"BOSS", "STAGE4_2", "BOSS_MOMS_HEART"})
MusicAPI.AddTrigger("BOSS_MOMS_HEART_MAUSOLEUM", Music.MUSIC_MOMS_HEART_BOSS, {"BOSS", "STAGE3_2", "REPENTANCE", "BOSS_MOMS_HEART"})
MusicAPI.AddTrigger("BOSS_ISAAC", Music.MUSIC_ISAAC_BOSS, {"BOSS", "STAGE5", "STAGETYPE_WOTL"})
MusicAPI.AddTrigger("BOSS_SATAN", Music.MUSIC_SATAN_BOSS, {"BOSS", "STAGE5", "STAGETYPE_ORIGINAL", "BOSS_PHASE_TRANSITION"})
MusicAPI.AddTrigger("BOSS_MEGA_SATAN", Music.MUSIC_SATAN_BOSS, {"BOSS", "STAGE6"})
MusicAPI.AddTrigger("BOSS_LAMB", Music.MUSIC_DARKROOM_BOSS, {"BOSS", "STAGE6", "STAGETYPE_ORIGINAL"})
MusicAPI.AddTrigger("BOSS_BLUE_BABY_CHEST", Music.MUSIC_BLUEBABY_BOSS, {"BOSS", "STAGE6", "STAGETYPE_WOTL", "BOSS_BLUE_BABY"})
MusicAPI.AddTrigger("BOSS_BLUE_BABY_BLUE_WOMB", Music.MUSIC_BLUEBABY_BOSS, {"BOSS", "STAGE4_3", "BOSS_BLUE_BABY"})
MusicAPI.AddTrigger("BOSS_HUSH", Music.MUSIC_BLUEBABY_BOSS, {"BOSS", "STAGE4_3", "BOSS_PHASE_TRANSITION"})
MusicAPI.AddTrigger("BOSS_ULTRA_GREED", Music.MUSIC_ULTRAGREED_BOSS, {"BOSS", "STAGE7_GREED", "BOSS_ULTRA_GREED"})
MusicAPI.AddTrigger("BOSS_ULTRA_GREEDIER", Music.MUSIC_ULTRAGREED_BOSS, {"BOSS", "STAGE7_GREED", "BOSS_ULTRA_GREED", "BOSS_PHASE_TRANSITION"})
MusicAPI.AddTrigger("BOSS_DELIRIUM", Music.MUSIC_VOID_BOSS, {"BOSS", "STAGE7"})
MusicAPI.AddTrigger("BOSS_MOTHER", Music.MUSIC_MOTHER_BOSS, {"BOSS", "STAGE4_2", "REPENTANCE"})
MusicAPI.AddTrigger("BOSS_DOGMA", Music.MUSIC_DOGMA_BOSS, {"BOSS", "STAGE8", "REPENTANCE"})
MusicAPI.AddTrigger("BOSS_BEAST", Music.MUSIC_BEAST_BOSS, {"BOSS", "STAGE8", "REPENTANCE"})

MusicAPI.AddTrigger("ROOM_SHOP", Music.MUSIC_SHOP_ROOM, {})
MusicAPI.AddTrigger("ROOM_TREASURE", nil, {})
MusicAPI.AddTrigger("ROOM_BOSS_CLEAR", Music.MUSIC_BOSS_OVER, {"BOSS_CLEAR"})
MusicAPI.AddTrigger("ROOM_BOSS_CLEAR_TWISTED", Music.MUSIC_BOSS_OVER_TWISTED, {})
MusicAPI.AddTrigger("ROOM_MINIBOSS_ACTIVE", nil, {})
MusicAPI.AddTrigger("ROOM_MINIBOSS_CLEAR", nil, {"BOSS_CLEAR"})
MusicAPI.AddTrigger("ROOM_SECRET", Music.MUSIC_SECRET_ROOM, {"ROOM_SECRET"})
MusicAPI.AddTrigger("ROOM_SUPER_SECRET", Music.MUSIC_SECRET_ROOM2, {"ROOM_SECRET"})
MusicAPI.AddTrigger("ROOM_ULTRA_SECRET", Music.MUSIC_SECRET_ROOM_ALT_ALT, {"ROOM_SECRET", "REPENTANCE"})
MusicAPI.AddTrigger("ROOM_ARCADE", Music.MUSIC_ARCADE_ROOM, {})
MusicAPI.AddTrigger("ROOM_CURSE", nil, {})
MusicAPI.AddTrigger("ROOM_CHALLENGE_NORMAL_INACTIVE", nil, {"ROOM_CHALLENGE_INACTIVE"})
MusicAPI.AddTrigger("ROOM_CHALLENGE_NORMAL_ACTIVE", Music.MUSIC_CHALLENGE_FIGHT, {"ROOM_CHALLENGE_ACTIVE"})
MusicAPI.AddTrigger("ROOM_CHALLENGE_NORMAL_CLEAR", Music.MUSIC_BOSS_OVER, {"ROOM_CHALLENGE_CLEAR", "BOSS_CLEAR"})
MusicAPI.AddTrigger("ROOM_CHALLENGE_BOSS_INACTIVE", nil, {"ROOM_CHALLENGE_INACTIVE"})
MusicAPI.AddTrigger("ROOM_CHALLENGE_BOSS_ACTIVE", Music.MUSIC_CHALLENGE_FIGHT, {"ROOM_CHALLENGE_ACTIVE"})
MusicAPI.AddTrigger("ROOM_CHALLENGE_BOSS_CLEAR", Music.MUSIC_BOSS_OVER, {"ROOM_CHALLENGE_CLEAR", "BOSS_CLEAR"})
MusicAPI.AddTrigger("ROOM_LIBRARY", Music.MUSIC_LIBRARY_ROOM, {})
MusicAPI.AddTrigger("ROOM_SACRIFICE", nil, {})
MusicAPI.AddTrigger("ROOM_DEVIL", Music.MUSIC_DEVIL_ROOM, {})
MusicAPI.AddTrigger("ROOM_ANGEL", Music.MUSIC_ANGEL_ROOM, {})
MusicAPI.AddTrigger("ROOM_DUNGEON", Music.MUSIC_DUNGEON, {})
MusicAPI.AddTrigger("ROOM_BOSS_RUSH_INACTIVE", nil, {})
MusicAPI.AddTrigger("ROOM_BOSS_RUSH_ACTIVE", Music.MUSIC_BOSS_RUSH, {})
MusicAPI.AddTrigger("ROOM_BOSS_RUSH_CLEAR", Music.MUSIC_BOSS_OVER, {"BOSS_CLEAR"})
MusicAPI.AddTrigger("ROOM_ISAACS", nil, {"ROOM_ISAACS"})
MusicAPI.AddTrigger("ROOM_BARREN", nil, {"ROOM_ISAACS"})
MusicAPI.AddTrigger("ROOM_CHEST", nil, {"ROOM_DOUBLE_KEY"})
MusicAPI.AddTrigger("ROOM_DICE", nil, {"ROOM_DOUBLE_KEY"})
MusicAPI.AddTrigger("ROOM_BLACK_MARKET", nil, {})
MusicAPI.AddTrigger("ROOM_GREED_EXIT", nil, {})
MusicAPI.AddTrigger("ROOM_PLANETARIUM", Music.MUSIC_PLANETARIUM, {"REPENTANCE"})
MusicAPI.AddTrigger("ROOM_TELEPORTER", nil, {"REPENTANCE"})
MusicAPI.AddTrigger("ROOM_TELEPORTER_EXIT", nil, {"REPENTANCE"})
MusicAPI.AddTrigger("ROOM_OTHER", nil, {})

MusicAPI.AddTrigger("JINGLE_BOSS", Music.MUSIC_JINGLE_BOSS, {"JINGLE"})
MusicAPI.AddTrigger("JINGLE_BOSS_OVER_REBIRTH", Music.MUSIC_JINGLE_BOSS_OVER, {"JINGLE", "JINGLE_BOSS_OVER"})
MusicAPI.AddTrigger("JINGLE_BOSS_OVER_AFTERBIRTH", Music.MUSIC_JINGLE_BOSS_OVER2, {"JINGLE", "JINGLE_BOSS_OVER"})
MusicAPI.AddTrigger("JINGLE_BOSS_OVER_REPENTANCE", Music.MUSIC_JINGLE_BOSS_OVER3, {"JINGLE", "JINGLE_BOSS_OVER", "REPENTANCE"})
MusicAPI.AddTrigger("JINGLE_ANGEL_ROOM", Music.MUSIC_JINGLE_HOLYROOM_FIND, {"JINGLE", "JINGLE_DEAL"})
MusicAPI.AddTrigger("JINGLE_SECRET_ROOM", Music.MUSIC_JINGLE_SECRETROOM_FIND, {"JINGLE"})
MusicAPI.AddTrigger("JINGLE_TREASURE_ROOM_0", Music.MUSIC_JINGLE_TREASUREROOM_ENTRY_0, {"JINGLE", "JINGLE_TREASURE_ROOM"})
MusicAPI.AddTrigger("JINGLE_TREASURE_ROOM_1", Music.MUSIC_JINGLE_TREASUREROOM_ENTRY_1, {"JINGLE", "JINGLE_TREASURE_ROOM"})
MusicAPI.AddTrigger("JINGLE_TREASURE_ROOM_2", Music.MUSIC_JINGLE_TREASUREROOM_ENTRY_2, {"JINGLE", "JINGLE_TREASURE_ROOM"})
MusicAPI.AddTrigger("JINGLE_TREASURE_ROOM_3", Music.MUSIC_JINGLE_TREASUREROOM_ENTRY_3, {"JINGLE", "JINGLE_TREASURE_ROOM"})
MusicAPI.AddTrigger("JINGLE_CHALLENGE_NORMAL_OUTRO", Music.MUSIC_JINGLE_CHALLENGE_OUTRO, {"JINGLE", "JINGLE_CHALLENGE_OUTRO"})
MusicAPI.AddTrigger("JINGLE_CHALLENGE_BOSS_OUTRO", Music.MUSIC_JINGLE_CHALLENGE_OUTRO, {"JINGLE", "JINGLE_CHALLENGE_OUTRO"})
MusicAPI.AddTrigger("JINGLE_GAME_OVER", Music.MUSIC_JINGLE_GAME_OVER, {"JINGLE"})
MusicAPI.AddTrigger("JINGLE_DEVIL_ROOM", Music.MUSIC_JINGLE_DEVILROOM_FIND, {"JINGLE", "JINGLE_DEAL"})
MusicAPI.AddTrigger("JINGLE_BOSS_RUSH_OUTRO", Music.MUSIC_JINGLE_BOSS_OVER, {"JINGLE", "JINGLE_BOSS_OVER"}) --check this
MusicAPI.AddTrigger("JINGLE_MOTHER_OVER", Music.MUSIC_JINGLE_MOTHER_OVER, {"JINGLE"})
MusicAPI.AddTrigger("JINGLE_DOGMA_OVER", Music.MUSIC_JINGLE_DOGMA_OVER, {"JINGLE"})
MusicAPI.AddTrigger("JINGLE_BEAST_OVER", Music.MUSIC_JINGLE_BEAST_OVER, {"JINGLE"})
MusicAPI.AddTrigger("JINGLE_STRANGE_DOOR", Music.MUSIC_STRANGE_DOOR_JINGLE, {"JINGLE"})

MusicAPI.AddTrigger("INTRO_MOTHERS_SHADOW", Music.MUSIC_MOTHERS_SHADOW_INTRO, {"INTRO"})
MusicAPI.AddTrigger("INTRO_DOGMA", Music.MUSIC_DOGMA_INTRO, {"INTRO"})

MusicAPI.AddTrigger("STATE_GAME_OVER", Music.MUSIC_GAME_OVER, {})
MusicAPI.AddTrigger("STATE_ASCENT", Music.MUSIC_REVERSE_GENESIS, {})

MusicAPI.AddTrigger("DIMENSION_DEATH_CERTIFICATE", Music.MUSIC_DARK_CLOSET, {})